PACKAGE_NAME="synosnap"
PACKAGE_VERSION="0.12.12"
PRE_BUILD="env CC=clang LLVM=1 ./genconfig.sh ${kernelver}"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build KERNELVERSION=${kernelver} CC=clang LLVM=1 modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build KERNELVERSION=${kernelver} clean"
BUILT_MODULE_NAME[0]="synosnap"
DEST_MODULE_LOCATION[0]="/kernel/drivers/block/"
AUTOINSTALL="yes"
